[package]
name = "canopy"
version = "0.1.0"
description = "Open-source Git client built for worktrees"
authors = ["Ivan Bondarenko"]
edition = "2021"

[lib]
name = "canopy_lib"
crate-type = ["staticlib", "cdylib", "rlib"]


[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
tauri = { version = "2", features = [] }
tauri-plugin-opener = "2"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
tauri-plugin-dialog = "2"

